services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: auth_db
    ports:
      - "6543:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  subscription-db:
    image: postgres:16
    container_name: subscription-db
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: subscription_db
    ports:
      - "6544:5432"
    volumes:
      - subscription_db_data:/var/lib/postgresql/data

  usage-db:
    image: postgres:16
    container_name: usage-db
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: usage_db
    ports:
      - "6545:5432"
    volumes:
      - usage_db_data:/var/lib/postgresql/data

  billing-db:
    image: postgres:16
    container_name: billing-db
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: billing_db
    ports:
      - "6546:5432"
    volumes:
      - billing_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  subscription_db_data:
  usage_db_data:
  billing_db_data:
